rvm:
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

env:
  - RAILS_VERSION="~> 3.1"
  - RAILS_VERSION="~> 3.2"
  - RAILS_VERSION="~> 4.0"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-19mode
    - rvm: jruby-head
